version: '3.8'

services:
  so-close-web:
    build: .
    container_name: so-close-local
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - ENV=development
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: so-close-network